"""changed media and course structure to establish a one to one relationship

Revision ID: 0348364e998a
Revises: 32c84f35ad1d
Create Date: 2025-08-30 17:44:10.943530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0348364e998a'
down_revision: Union[str, None] = '32c84f35ad1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'courses', ['image_id'])
    op.create_foreign_key(None, 'courses', 'media', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('courses', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('images', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'image_id')
    # ### end Alembic commands ###
