"""adding image in courses

Revision ID: 1666cea04cbc
Revises: 8b5906cd3ccf
Create Date: 2025-08-25 17:04:20.209847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1666cea04cbc'
down_revision: Union[str, None] = '8b5906cd3ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('images', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'images')
    # ### end Alembic commands ###
