"""init schema

Revision ID: 2d1b2b180c26
Revises: 
Create Date: 2025-08-25 16:36:43.777482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1b2b180c26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lesson_section_order', 'lessons', ['section_id', 'lesson_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lesson_section_order', 'lessons', type_='unique')
    # ### end Alembic commands ###
