"""added media table2

Revision ID: 32c84f35ad1d
Revises: 8cd85b19079d
Create Date: 2025-08-27 11:35:15.389897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c84f35ad1d'
down_revision: Union[str, None] = '8cd85b19079d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.Enum('image', 'video', name='media_type_enum'), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('secure_url', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("(resource_type = 'image' AND duration_ms IS NULL) OR resource_type = 'video'", name='image_no_duration'),
    sa.CheckConstraint('(width IS NULL OR width > 0) AND (height IS NULL OR height > 0)', name='dims_positive'),
    sa.CheckConstraint('bytes >= 0', name='bytes_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_media_public_id')
    )
    op.create_index(op.f('ix_media_deleted_by'), 'media', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_media_public_id'), 'media', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_public_id'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_by'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
