"""added image in project model

Revision ID: 56634ff14f0c
Revises: 0348364e998a
Create Date: 2025-08-31 00:31:00.460007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56634ff14f0c'
down_revision: Union[str, None] = '0348364e998a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'projects', ['image_id'])
    op.create_foreign_key(None, 'projects', 'media', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', 'image_id')
    # ### end Alembic commands ###
