"""added media table

Revision ID: 8cd85b19079d
Revises: 1666cea04cbc
Create Date: 2025-08-27 11:32:46.375029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd85b19079d'
down_revision: Union[str, None] = '1666cea04cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_details', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('project_details', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('project_details', sa.Column('tech_stack', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'project_details', ['project_id'])
    op.drop_constraint('project_details_id_fkey', 'project_details', type_='foreignkey')
    op.create_foreign_key(None, 'project_details', 'projects', ['project_id'], ['id'])
    op.drop_column('project_details', 'markdown_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_details', sa.Column('markdown_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_details', type_='foreignkey')
    op.create_foreign_key('project_details_id_fkey', 'project_details', 'projects', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_details', type_='unique')
    op.drop_column('project_details', 'tech_stack')
    op.drop_column('project_details', 'content')
    op.drop_column('project_details', 'project_id')
    # ### end Alembic commands ###
