"""project_key_modifed to image_id now working

Revision ID: abb15ee92873
Revises: ffc4eadc86d0
Create Date: 2025-08-31 00:57:33.496112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb15ee92873'
down_revision: Union[str, None] = 'ffc4eadc86d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
