"""add Profile Model

Revision ID: b030b4eed9a2
Revises: f3bbcbea5a6a
Create Date: 2025-09-06 16:18:29.501752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b030b4eed9a2'
down_revision: Union[str, None] = 'f3bbcbea5a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
