"""course, media and project updating

Revision ID: d724e4d9a651
Revises: abb15ee92873
Create Date: 2025-09-03 13:37:22.634663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd724e4d9a651'
down_revision: Union[str, None] = 'abb15ee92873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_medias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_course_medias_course_id'), 'course_medias', ['course_id'], unique=False)
    op.create_table('project_medias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_project_medias_project_id'), 'project_medias', ['project_id'], unique=False)
    op.add_column('media', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_media_course_id'), 'media', ['course_id'], unique=True)
    op.create_index(op.f('ix_media_project_id'), 'media', ['project_id'], unique=True)
    op.create_foreign_key(None, 'media', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_project_id'), table_name='media')
    op.drop_index(op.f('ix_media_course_id'), table_name='media')
    op.drop_column('media', 'course_id')
    op.drop_column('media', 'project_id')
    op.drop_index(op.f('ix_project_medias_project_id'), table_name='project_medias')
    op.drop_table('project_medias')
    op.drop_index(op.f('ix_course_medias_course_id'), table_name='course_medias')
    op.drop_table('course_medias')
    # ### end Alembic commands ###
