"""password_update issue fixed and profile issue fixed

Revision ID: d99228772778
Revises: 52876a80e3ab
Create Date: 2025-09-06 22:06:19.544329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d99228772778"
down_revision: Union[str, None] = "52876a80e3ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("media_project_owner_id_fkey", "media", type_="foreignkey")
    op.drop_constraint("media_course_owner_id_fkey", "media", type_="foreignkey")
    op.create_foreign_key(
        None, "media", "courses", ["course_owner_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "media", "projects", ["project_owner_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("users", sa.Column("password", sa.String(length=255), nullable=True))
    op.execute(
        """
        UPDATE users
        SET password = password_hash
        WHERE password IS NULL
    """
    )
    op.alter_column("users", "password", nullable=False)
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "password")
    op.drop_constraint(None, "media", type_="foreignkey")
    op.drop_constraint(None, "media", type_="foreignkey")
    op.create_foreign_key(
        "media_course_owner_id_fkey",
        "media",
        "courses",
        ["course_owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "media_project_owner_id_fkey",
        "media",
        "projects",
        ["project_owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
