"""added  tags, technologies, features

Revision ID: f3bbcbea5a6a
Revises: 8fbc369d3457
Create Date: 2025-09-03 21:11:31.494689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bbcbea5a6a'
down_revision: Union[str, None] = '8fbc369d3457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_media_relations')
    op.drop_constraint('courses_image_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'media', ['image_id'], ['id'])
    op.drop_constraint('media_project_id_fkey', 'media', type_='foreignkey')
    op.drop_constraint('media_course_id_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'media', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_course_id_fkey', 'media', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('media_project_id_fkey', 'media', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_image_id_fkey', 'courses', 'media', ['image_id'], ['id'], ondelete='SET NULL')
    op.create_table('project_media_relations',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='project_media_relations_media_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_media_relations_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'media_id', name='project_media_relations_pkey')
    )
    # ### end Alembic commands ###
