// Dummy data for test mode
import type { Project, Course, Section, Lesson, Profile, Lead } from "./types";

export const dummyProjects: Project[] = [
  {
    id: "1",
    title: "E-Commerce Platform",
    slug: "e-commerce-platform",
    description:
      "# E-Commerce Platform\n\nA modern e-commerce solution with real-time inventory management, payment processing, and customer analytics.\n\n## Features\n- Product catalog management\n- Shopping cart & checkout\n- Order tracking\n- Customer reviews",
    thumbnail: "/ecommerce-dashboard.png",
    status: "published",
    tags: ["React", "Node.js", "PostgreSQL"],
    visits: 12500,
    leads_count: 245,
    conversion_rate: 3.2,
    owner_id: "1",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-03-20T15:30:00Z",
  },
  {
    id: "2",
    title: "Learning Management System",
    slug: "learning-management-system",
    description:
      "# LMS Platform\n\nComprehensive learning management system for online education.\n\n## Capabilities\n- Course creation\n- Student progress tracking\n- Certificates generation\n- Video streaming",
    thumbnail: "/learning-management-system.png",
    status: "published",
    tags: ["Next.js", "Python", "AWS"],
    visits: 8900,
    leads_count: 178,
    conversion_rate: 2.8,
    owner_id: "1",
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2024-03-18T11:20:00Z",
  },
  {
    id: "3",
    title: "CRM Dashboard",
    slug: "crm-dashboard",
    description:
      "# CRM Dashboard\n\nCustomer relationship management dashboard with advanced analytics.",
    thumbnail: "/crm-dashboard-analytics.jpg",
    status: "draft",
    tags: ["Vue.js", "Django", "Redis"],
    visits: 0,
    leads_count: 0,
    conversion_rate: 0,
    owner_id: "1",
    created_at: "2024-03-10T14:00:00Z",
    updated_at: "2024-03-10T14:00:00Z",
  },
  {
    id: "4",
    title: "Mobile Banking App",
    slug: "mobile-banking-app",
    description:
      "# Mobile Banking\n\nSecure mobile banking application with biometric authentication.",
    thumbnail: "/mobile-banking-app.png",
    status: "archived",
    tags: ["React Native", "Go", "MongoDB"],
    visits: 45000,
    leads_count: 890,
    conversion_rate: 4.1,
    owner_id: "1",
    created_at: "2023-06-15T10:00:00Z",
    updated_at: "2024-01-05T09:00:00Z",
  },
];

export const dummyCourses: Course[] = [
  {
    id: "1",
    title: "Complete React Masterclass",
    slug: "complete-react-masterclass",
    description:
      "Master React from basics to advanced concepts including hooks, context, and performance optimization.",
    thumbnail: "/react-course-thumbnail.jpg",
    price: 99.99,
    status: "published",
    sections_count: 8,
    lessons_count: 45,
    students_count: 1250,
    progress: 100,
    owner_id: "1",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-03-15T14:30:00Z",
  },
  {
    id: "2",
    title: "Node.js Backend Development",
    slug: "nodejs-backend-development",
    description:
      "Build scalable backend applications with Node.js, Express, and MongoDB.",
    thumbnail: "/nodejs-backend-course.png",
    price: 79.99,
    status: "published",
    sections_count: 6,
    lessons_count: 32,
    students_count: 890,
    progress: 85,
    owner_id: "1",
    created_at: "2024-02-05T09:00:00Z",
    updated_at: "2024-03-10T11:00:00Z",
  },
  {
    id: "3",
    title: "Python for Data Science",
    slug: "python-data-science",
    description:
      "Learn Python programming for data analysis, visualization, and machine learning.",
    thumbnail: "/python-data-science-course.png",
    price: 0,
    status: "draft",
    sections_count: 4,
    lessons_count: 18,
    students_count: 0,
    progress: 45,
    owner_id: "1",
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-20T16:00:00Z",
  },
  {
    id: "4",
    title: "UI/UX Design Fundamentals",
    slug: "ui-ux-design-fundamentals",
    description:
      "Essential design principles for creating beautiful and user-friendly interfaces.",
    thumbnail: "/ui-ux-design-course.png",
    price: 49.99,
    status: "hidden",
    sections_count: 5,
    lessons_count: 25,
    students_count: 450,
    progress: 100,
    owner_id: "1",
    created_at: "2023-11-15T10:00:00Z",
    updated_at: "2024-02-28T09:00:00Z",
  },
];

export const dummySections: Section[] = [
  // Course 1 sections
  {
    id: "1",
    title: "Introduction to React",
    summary:
      "Getting started with React, understanding JSX, and setting up your development environment.",
    order: 1,
    course_id: "1",
    lessons_count: 5,
    duration_minutes: 45,
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "2",
    title: "React Hooks Deep Dive",
    summary:
      "Master useState, useEffect, useContext, useReducer, and custom hooks.",
    order: 2,
    course_id: "1",
    lessons_count: 8,
    duration_minutes: 90,
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
  },
  {
    id: "3",
    title: "State Management",
    summary:
      "Context API, Redux, Zustand, and choosing the right state management solution.",
    order: 3,
    course_id: "1",
    lessons_count: 6,
    duration_minutes: 75,
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Performance Optimization",
    summary:
      "React.memo, useMemo, useCallback, code splitting, and lazy loading.",
    order: 4,
    course_id: "1",
    lessons_count: 5,
    duration_minutes: 60,
    created_at: "2024-01-18T10:00:00Z",
    updated_at: "2024-01-18T10:00:00Z",
  },
  // Course 2 sections
  {
    id: "5",
    title: "Node.js Fundamentals",
    summary: "Understanding Node.js runtime, modules, and the event loop.",
    order: 1,
    course_id: "2",
    lessons_count: 6,
    duration_minutes: 50,
    created_at: "2024-02-05T10:00:00Z",
    updated_at: "2024-02-05T10:00:00Z",
  },
  {
    id: "6",
    title: "Express.js Framework",
    summary: "Building REST APIs with Express, middleware, and routing.",
    order: 2,
    course_id: "2",
    lessons_count: 7,
    duration_minutes: 80,
    created_at: "2024-02-08T10:00:00Z",
    updated_at: "2024-02-08T10:00:00Z",
  },
];

export const dummyLessons: Lesson[] = [
  // Section 1 lessons
  {
    id: "1",
    title: "What is React?",
    content:
      "# What is React?\n\nReact is a JavaScript library for building user interfaces. It was developed by Facebook and is now maintained by Meta.\n\n## Key Concepts\n\n- **Components**: Reusable UI building blocks\n- **Virtual DOM**: Efficient rendering mechanism\n- **JSX**: JavaScript XML syntax extension\n\n## Why React?\n\n1. Component-based architecture\n2. Large ecosystem and community\n3. Excellent developer tools\n4. Strong corporate backing",
    content_type: "text",
    duration_minutes: 10,
    order: 1,
    is_published: true,
    section_id: "1",
    slug: "what-is-react",
    tags: ["introduction", "basics"],
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "2",
    title: "Setting Up Your Environment",
    content:
      "# Development Environment Setup\n\nLearn how to set up your React development environment with Vite or Create React App.",
    content_type: "video",
    duration_minutes: 15,
    order: 2,
    is_published: true,
    section_id: "1",
    slug: "setting-up-environment",
    tags: ["setup", "tooling"],
    created_at: "2024-01-10T11:00:00Z",
    updated_at: "2024-01-10T11:00:00Z",
  },
  {
    id: "3",
    title: "Understanding JSX",
    content:
      "# JSX - JavaScript XML\n\nJSX allows you to write HTML-like code in your JavaScript files.",
    content_type: "text",
    duration_minutes: 12,
    order: 3,
    is_published: true,
    section_id: "1",
    slug: "understanding-jsx",
    tags: ["jsx", "syntax"],
    created_at: "2024-01-10T12:00:00Z",
    updated_at: "2024-01-10T12:00:00Z",
  },
  {
    id: "4",
    title: "Quiz: React Basics",
    content: null,
    content_type: "quiz",
    duration_minutes: 8,
    order: 4,
    is_published: true,
    section_id: "1",
    slug: "quiz-react-basics",
    tags: ["quiz", "assessment"],
    created_at: "2024-01-10T13:00:00Z",
    updated_at: "2024-01-10T13:00:00Z",
  },
  // Section 2 lessons
  {
    id: "5",
    title: "Introduction to Hooks",
    content:
      "# React Hooks\n\nHooks are functions that let you use state and other React features in functional components.",
    content_type: "video",
    duration_minutes: 20,
    order: 1,
    is_published: true,
    section_id: "2",
    slug: "introduction-to-hooks",
    tags: ["hooks", "fundamentals"],
    created_at: "2024-01-12T10:00:00Z",
    updated_at: "2024-01-12T10:00:00Z",
  },
  {
    id: "6",
    title: "useState Hook",
    content:
      "# useState Hook\n\nThe useState hook lets you add state to functional components.",
    content_type: "text",
    duration_minutes: 15,
    order: 2,
    is_published: true,
    section_id: "2",
    slug: "usestate-hook",
    tags: ["hooks", "state"],
    created_at: "2024-01-12T11:00:00Z",
    updated_at: "2024-01-12T11:00:00Z",
  },
  {
    id: "7",
    title: "useEffect Hook",
    content:
      "# useEffect Hook\n\nThe useEffect hook lets you perform side effects in functional components.",
    content_type: "video",
    duration_minutes: 25,
    order: 3,
    is_published: false,
    section_id: "2",
    slug: "useeffect-hook",
    tags: ["hooks", "effects"],
    created_at: "2024-01-12T12:00:00Z",
    updated_at: "2024-01-12T12:00:00Z",
  },
];

export const dummyProfile: Profile = {
  id: "1",
  name: "Alex Johnson",
  title: "Senior Full Stack Developer",
  tagline: "Building scalable web applications with modern technologies",
  avatar: "/professional-developer-avatar.png",
  location: "San Francisco, CA",
  bio: "# About Me\n\nI am a passionate software developer with over 8 years of experience in building web applications. I specialize in React, Node.js, and cloud technologies.\n\n## My Journey\n\nStarted coding at 15, built my first startup at 22, and have been helping companies scale their engineering teams ever since.\n\n## What I Do\n\n- Full-stack web development\n- Technical architecture consulting\n- Team mentoring and training",
  linkedin_url: "https://linkedin.com/in/alexjohnson",
  youtube_url: "https://youtube.com/@alexcodes",
  website_url: "https://alexjohnson.dev",
  skills: [
    "React",
    "TypeScript",
    "Node.js",
    "Python",
    "AWS",
    "PostgreSQL",
    "Docker",
    "Kubernetes",
  ],
  experience: [
    {
      id: "1",
      role: "Senior Full Stack Developer",
      organization: "TechCorp Inc.",
      start_date: "2022-01-01",
      end_date: null,
      description:
        "Leading the development of enterprise SaaS products serving 100k+ users.",
      is_current: true,
    },
    {
      id: "2",
      role: "Full Stack Developer",
      organization: "StartupXYZ",
      start_date: "2019-06-01",
      end_date: "2021-12-31",
      description: "Built and scaled the core platform from 0 to 50k users.",
      is_current: false,
    },
    {
      id: "3",
      role: "Frontend Developer",
      organization: "WebAgency Co.",
      start_date: "2017-03-01",
      end_date: "2019-05-31",
      description: "Developed responsive web applications for various clients.",
      is_current: false,
    },
  ],
  user_id: "1",
  created_at: "2024-01-01T10:00:00Z",
  updated_at: "2024-03-15T14:30:00Z",
};

export const dummyLeads: Lead[] = [
  {
    id: "1",
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "+1 555-0123",
    country: "United States",
    timezone: "America/New_York",
    status: "new",
    source: "landing",
    notes:
      "Interested in the React course. Mentioned she has 2 years of JavaScript experience.",
    owner_id: "1",
    utm_campaign: "spring_sale",
    utm_source: "google",
    created_at: "2024-03-20T10:00:00Z",
    updated_at: "2024-03-20T10:00:00Z",
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    phone: "+1 555-0456",
    country: "Canada",
    timezone: "America/Toronto",
    status: "contacted",
    source: "course",
    notes:
      "Had a call yesterday. Following up next week about enterprise pricing.",
    owner_id: "1",
    utm_campaign: null,
    utm_source: "organic",
    created_at: "2024-03-18T14:00:00Z",
    updated_at: "2024-03-19T16:30:00Z",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.r@example.com",
    phone: "+44 20 7123 4567",
    country: "United Kingdom",
    timezone: "Europe/London",
    status: "converted",
    source: "webinar",
    notes: "Purchased the React Masterclass after attending the free webinar.",
    owner_id: "1",
    utm_campaign: "webinar_march",
    utm_source: "linkedin",
    created_at: "2024-03-10T09:00:00Z",
    updated_at: "2024-03-15T11:00:00Z",
  },
  {
    id: "4",
    name: "David Park",
    email: "david.park@example.com",
    phone: null,
    country: "South Korea",
    timezone: "Asia/Seoul",
    status: "lost",
    source: "referral",
    notes: "Budget constraints. May revisit in Q3.",
    owner_id: "1",
    utm_campaign: null,
    utm_source: "referral",
    created_at: "2024-02-28T08:00:00Z",
    updated_at: "2024-03-05T10:00:00Z",
  },
];

// Helper to generate unique IDs
export const generateId = () => Math.random().toString(36).substring(2, 15);
